version: "2"
services:

  auth:
    image: openlmis/auth
    links:
      - db
      - log
    env_file: .env

  db:
    image: openlmis/postgres:12-debezium
    ports:
      - "5432"
    env_file: .env

  log:
    image: openlmis/rsyslog:3
    volumes:
      - '../logs/auth:/var/log'
