version: "2"
services:

  auth:
    image: openlmis/auth
    links:
      - db
      - log
    env_file: .env

  db:
    image: openlmis/postgres:9.6
    ports:
      - "8766:5432"
    env_file: .env

  log:
    image: openlmis/rsyslog:1
    volumes:
      - '../logs/auth:/var/log'

  consul:
    command: -server -bootstrap
    image: gliderlabs/consul-server
    ports:
      - "8300"
      - "8400"
      - "8500"
      - "53"
