version: "2"
services:

  auth:
    image: openlmis/auth
    links:
      - db
      - log
    env_file: .env

  db:
    image: openlmis/postgres:9.4
    ports:
      - "8766:5432"
    env_file: .env

  log:
    image: openlmis/rsyslog
    volumes:
      - '../logs/auth:/var/log'
