version: "2"
services:

  auth:
    image: openlmis/dev:9
    ports:
      - "5005:5005"
      - "8080:8080"
    volumes:
      - '.:/app'
      - 'gradlecache:/gradle'

  db:
    ports:
      - "5432"

volumes:
  gradlecache:
    external: false
