version: "2"
services:
  auth:
    image: openlmis/auth
    links:
      - db
      - log
    env_file: .env
    ports:
      - "8080"
  db:
    image: openlmis/postgres
    env_file: .env
    ports:
      - "8766:5432"
  log:
    image: openlmis/rsyslog
    volumes:
      - '../logs/auth:/var/log'
