version: "2"
services:

  builder:
    image: openlmis/dev:1
    links:
      - db
      - log
    volumes:
      - '.:/app'
    command:
      - './build.sh'
    environment:
      GRADLE_OPTS: '-Dorg.gradle.daemon=false'
    env_file: .env

  sonar:
    image: openlmis/dev:1
    volumes:
      - '.:/app'
    entrypoint:
      - 'gradle'
    command:
      - 'clean'
      - 'sonarqube'
    environment:
      GRADLE_OPTS: '-Dorg.gradle.daemon=false $SONAR_LOGIN $SONAR_PASSWORD'
    env_file: .env

  demo-data:
    image: openlmis/dev:1
    links:
      - db
      - log
    volumes:
      - '.:/app'
    entrypoint:
      - 'gradle'
    command:
      - 'demoDataSeed'
    environment:
      GRADLE_OPTS: '-Dorg.gradle.daemon=false'
    env_file: .env

  image:
    build: .
    image: openlmis/auth

  db:
    image: openlmis/postgres:9.4
    ports:
      - "5432"
    env_file: .env

  log:
    image: openlmis/rsyslog:1
    volumes:
      - '../logs/auth:/var/log'
