version: "2"
services:
  builder:
    image: openlmis/dev
    links:
      - db
      - log
    volumes:
      - '.:/app'
    entrypoint:
      - 'gradle'
    command:
      - './build.sh'
    environment:
      GRADLE_OPTS: '-Dorg.gradle.daemon=false'
    env_file: .env
  image:
    build: .
    image: openlmis/auth
  db:
    image: openlmis/postgres
    ports:
      - "5432"
    env_file: .env
  log:
    image: openlmis/rsyslog
    volumes:
      - '../logs/auth:/var/log'
